<assets path="assets/week7"    library="week6"    exclude="*.ogg" if="web"/>
<assets path="assets/week7"    library="week6"    exclude="*.mp3" unless="web"/>

<assets path="assets/videos" exclude="*.mp3" if="web"/>
<assets path="assets/videos" exclude="*.ogg" unless="web"/>

<assets path="plugins/" rename='' if="windows"/>
<assets path="dlls/" rename='' if="windows"/>

inline static public function video(key:String, ?library:String)
{
	trace('assets/videos/$key.mp4');
	return getPath('videos/$key.mp4', BINARY, library);
}

var isCutscene:Bool = false;

new FlxTimer().start(1, function(tmr:FlxTimer)
{
	LoadingState.loadAndSwitchState(new PlayState(), true);
});

var video:MP4Handler = new MP4Handler();

			if (curWeek == 0 && !isCutscene) // Checks if the current week is garAlley.
			new FlxTimer().start(1, function(tmr:FlxTimer)
			{
				{
					video.playMP4(Paths.video('intro'));
					video.finishCallback = function()
					{
						LoadingState.loadAndSwitchState(new PlayState());
					}
					
					isCutscene = true;
				}
			});
			else
			{
				new FlxTimer().start(1, function(tmr:FlxTimer)
				{
					if (isCutscene)
						video.onVLCComplete();

					LoadingState.loadAndSwitchState(new PlayState(), true);
				});
			}
		}
    var video:MP4Handler = new MP4Handler();

video.playMP4(Paths.video('yourvideonamehere'));
video.finishCallback = function()
{
	LoadingState.loadAndSwitchState(new PlayState());
}
FlxTransitionableState.skipNextTransIn = true;
FlxTransitionableState.skipNextTransOut = true;

var sprite:FlxSprite = new FlxSprite(0,0);

var video:MP4Handler = new MP4Handler();
video.playMP4(Paths.video('yourvideonamehere'), null, sprite); // make the transition null so it doesn't take you out of this state

add(sprite);
